# -*- coding: utf-8 -*-
"""OpenVINO-ColabNotebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/abhik-99/OpenDevLibrary/blob/master/OpenDevNotebook-CPU-modified.ipynb
"""

#Defining the Important Paths

file_name = "l_openvino_toolkit_p_2020.1.023.tgz" #change the filename if version does not match
dir_name = file_name[:-4]
install_dir = "/opt/intel/openvino/"
deployment_tools = install_dir+"deployment_tools/"
model_optimizer = install_dir+"deployment_tools/model_optimizer/"
model_zoo = deployment_tools+"open_model_zoo/"

!wget "https://storage.googleapis.com/open_vino_public/l_openvino_toolkit_p_2020.1.023.tgz"

!tar -xzf l_openvino_toolkit_p_2020.1.023.tgz
!sudo -E $dir_name/install_openvino_dependencies.sh
!sed -i 's/decline/accept/g' $dir_name/silent.cfg
!sed -i 's/#INTEL_SW_IMPROVEMENT/INTEL_SW_IMPROVEMENT/g' $dir_name/silent.cfg
!sudo ./$dir_name/install.sh --silent $dir_name/silent.cfg
!sudo -E $install_dir/install_dependencies/install_openvino_dependencies.sh
!source $install_dir/bin/setupvars.sh

frameworks = ['tf','mxnet','onnx','kaldi','all']
choices = dict(zip(range(1,6),frameworks))
print("""Please enter the Choice of framework you want to work with:
\n(Note: You should only install for the ones you would be using.
Incase of needing to install for more than one but not all, rerun this cell and 
install the pre-requisites one by one.)
""")
for x in choices:
  print(x,choices[x])
choice = eval(input("Please enter your choice: "))
print("Choice is",choice,":",choices[choice])
if choice != 5:
   pre_install = model_optimizer + "install_prerequisites/install_prerequisites.sh "+choices[choice]
   !sudo $pre_install
elif choice == 5:
  # for x in choices:
  #   pre_install = model_optimizer + "install_prerequisites/install_prerequisites.sh "+choices[x]
  #   !sudo $pre_install
   !sudo $model_optimizer/install_prerequisites/install_prerequisites.sh
else:
  print("Wrong Choice! Please rerun this cell and enter the correct choice!")

!sudo $deployment_tools/demo/demo_squeezenet_download_convert_run.sh